---
  - name: "testing"
    hosts: localhost
    connection: local
    tasks:
    
    - name: display warning on login
      ansible.builtin.shell:
        cmd: "ls -l"
      register: "result"

    - debug: var=result.stdout_lines

    - name: change login message
      ansible.builtin.copy:
        src: "./files/motd"
        dest: "/etc/motd"
        remote_src: yes
        force: yes

    - name: show contents
      ansible.builtin.shell:
        cmd: "cat /etc/motd"
      register: "content"

    - debug: var=content.stdout_lines